global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'vllm-server'
    static_configs:
      - targets: ['vllm-server:8001']
    metrics_path: '/v1/metrics'
    scrape_interval: 5s
    scrape_timeout: 3s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  - job_name: 'kong-gateway'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 30s

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

