name: Auto-Specializer

on:
  push:
    paths:
      - 'src/models/specializer/**'
  pull_request:
    paths:
      - 'src/models/specializer/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/auto-specializer.txt
        pip install pytest pytest-cov
    
    - name: Test with pytest
      run: |
        pytest src/models/specializer/tests/ --cov=src/models/specializer --cov-report=xml
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: auto-specializer
    
    - name: Build Docker image
      run: |
        docker build -t neuroweaver/auto-specializer:${{ github.sha }} -f docker/auto-specializer/Dockerfile .
    
    - name: Push to ECR
      if: github.event_name != 'pull_request'
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
      run: |
        docker tag neuroweaver/auto-specializer:${{ github.sha }} ${{ secrets.AWS_ECR_REGISTRY }}/neuroweaver/auto-specializer:${{ github.sha }}
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/neuroweaver/auto-specializer:${{ github.sha }}