name: NeuroWeaver CI/CD Pipeline

on:
  push:
    branches: [ main, develop, feature/* ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  pull_request:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'development'
        type: choice
        options:
        - development
        - testing
        - staging
        - production

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
      python-cache-key: ${{ steps.python-cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Determine components to build
        id: set-matrix
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, only build components with changes
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }}...HEAD)
            COMPONENTS=()
            
            for COMPONENT in template-system auto-specializer inference-weaver dataset-refinement costguard-dashboard workflow-ui; do
              if echo "$CHANGED_FILES" | grep -q "src/$COMPONENT/"; then
                COMPONENTS+=("$COMPONENT")
              fi
            done
            
            # If no components have changes, build all
            if [ ${#COMPONENTS[@]} -eq 0 ]; then
              COMPONENTS=(template-system auto-specializer inference-weaver dataset-refinement costguard-dashboard workflow-ui)
            fi
          else
            # For direct pushes, build all components
            COMPONENTS=(template-system auto-specializer inference-weaver dataset-refinement costguard-dashboard workflow-ui)
          fi
          
          echo "matrix={\"component\":[\"$(IFS=\\\",\\\"; echo "${COMPONENTS[*]}")\"]}" >> $GITHUB_OUTPUT
      
      - name: Generate Python cache key
        id: python-cache-key
        run: echo "key=neuroweaver-python-$(date +'%Y-%m')" >> $GITHUB_OUTPUT

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements/${{ matrix.component }}.txt
    
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ needs.setup.outputs.python-cache-key }}-${{ matrix.component }}-${{ hashFiles('requirements/${{ matrix.component }}.txt') }}
        restore-keys: |
          ${{ needs.setup.outputs.python-cache-key }}-${{ matrix.component }}-
          ${{ needs.setup.outputs.python-cache-key }}-
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements/${{ matrix.component }}.txt ]; then pip install -r requirements/${{ matrix.component }}.txt; fi
        pip install pytest pytest-cov flake8
    
    - name: Lint with flake8
      run: |
        flake8 src/${{ matrix.component }} --count --select=E9,F63,F7,F82 --show-source --statistics
    
    - name: Test with pytest
      run: |
        pytest src/${{ matrix.component }}/tests/ --cov=src/${{ matrix.component }} --cov-report=xml -v
    
    - name: Upload coverage report
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: ${{ matrix.component }}
    
    - name: Build Docker image
      run: |
        docker build -t neuroweaver/${{ matrix.component }}:${{ github.sha }} -f docker/${{ matrix.component }}/Dockerfile .
    
    - name: Cache Docker image
      uses: actions/cache@v3
      with:
        path: /tmp/docker-images/${{ matrix.component }}.tar
        key: docker-${{ matrix.component }}-${{ github.sha }}
      
    - name: Save Docker image
      run: |
        mkdir -p /tmp/docker-images
        docker save neuroweaver/${{ matrix.component }}:${{ github.sha }} > /tmp/docker-images/${{ matrix.component }}.tar
    
    - name: Push to ECR
      if: github.event_name != 'pull_request'
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry: ${{ secrets.AWS_ECR_REGISTRY }}
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
      run: |
        docker tag neuroweaver/${{ matrix.component }}:${{ github.sha }} ${{ secrets.AWS_ECR_REGISTRY }}/neuroweaver/${{ matrix.component }}:${{ github.sha }}
        docker push ${{ secrets.AWS_ECR_REGISTRY }}/neuroweaver/${{ matrix.component }}:${{ github.sha }}

  integration-test:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: requirements/integration.txt
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements/integration.txt
    
    - name: Load Docker images
      run: |
        for component in template-system auto-specializer inference-weaver dataset-refinement costguard-dashboard workflow-ui; do
          if [ -f /tmp/docker-images/$component.tar ]; then
            docker load < /tmp/docker-images/$component.tar
          fi
        done
    
    - name: Set up integration environment
      run: |
        docker-compose -f docker-compose.integration.yml up -d
    
    - name: Run integration tests in parallel
      run: |
        pytest integration_tests/ -xvs --junitxml=integration-results.xml -n auto
    
    - name: Upload test results
      uses: actions/upload-artifact@v3
      with:
        name: integration-test-results
        path: integration-results.xml
        retention-days: 5
    
    - name: Tear down integration environment
      if: always()
      run: |
        docker-compose -f docker-compose.integration.yml down

  deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    environment:
      name: ${{ github.event.inputs.environment || 'development' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.0.0
        terraform_wrapper: false
    
    - name: Cache Terraform
      uses: actions/cache@v3
      with:
        path: |
          terraform/${{ github.event.inputs.environment || 'development' }}/.terraform
          terraform/${{ github.event.inputs.environment || 'development' }}/.terraform.lock.hcl
        key: terraform-${{ github.event.inputs.environment || 'development' }}-${{ hashFiles('terraform/${{ github.event.inputs.environment || 'development' }}/*.tf') }}
        restore-keys: |
          terraform-${{ github.event.inputs.environment || 'development' }}-
    
    - name: Terraform Init
      run: |
        cd terraform/${{ github.event.inputs.environment || 'development' }}
        terraform init -input=false
    
    - name: Terraform Plan
      run: |
        cd terraform/${{ github.event.inputs.environment || 'development' }}
        terraform plan -input=false -out=tfplan
    
    - name: Terraform Apply
      if: github.event.inputs.environment != 'production' || github.ref == 'refs/heads/main'
      run: |
        cd terraform/${{ github.event.inputs.environment || 'development' }}
        terraform apply -auto-approve tfplan
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Setup Helm
      uses: azure/setup-helm@v3
      with:
        version: 'latest'
    
    - name: Deploy with Helm
      run: |
        helm upgrade --install neuroweaver ./helm/neuroweaver \
          --namespace neuroweaver-${{ github.event.inputs.environment || 'development' }} \
          --create-namespace \
          --set environment=${{ github.event.inputs.environment || 'development' }} \
          --set imageTag=${{ github.sha }} \
          --values ./helm/values-${{ github.event.inputs.environment || 'development' }}.yaml
    
    - name: Verify deployment
      run: |
        kubectl rollout status deployment/neuroweaver-api -n neuroweaver-${{ github.event.inputs.environment || 'development' }} --timeout=300s
        kubectl rollout status deployment/neuroweaver-frontend -n neuroweaver-${{ github.event.inputs.environment || 'development' }} --timeout=300s

  monitor:
    needs: deploy
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'
    
    - name: Get deployment status
      run: |
        kubectl get pods -n neuroweaver-${{ github.event.inputs.environment || 'development' }}
        kubectl get services -n neuroweaver-${{ github.event.inputs.environment || 'development' }}
    
    - name: Check monitoring dashboards
      run: |
        curl -s -o /dev/null -w "%{http_code}" https://grafana.${{ secrets.DOMAIN }}/api/health
    
    - name: Run smoke tests
      run: |
        python monitoring/smoke_tests.py --environment ${{ github.event.inputs.environment || 'development' }}
    
    - name: Send deployment notification
      uses: slackapi/slack-github-action@v1.23.0
      with:
        channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
        slack-message: "Deployment to ${{ github.event.inputs.environment || 'development' }} completed successfully. Monitoring checks passed."
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
