name: Security Scan

on:
  schedule:
    - cron: '0 0 * * *'  # Daily at midnight
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.AWS_ECR_REGISTRY }}/neuroweaver/template-system:latest
        format: 'sarif'
        output: 'trivy-results.sarif'
    
    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'
    
    - name: Run dependency check
      run: |
        pip install safety
        safety check -r requirements/template-system.txt --output json > safety-results.json
        safety check -r requirements/auto-specializer.txt --output json > safety-results-auto-specializer.json
    
    - name: Upload dependency check results
      uses: actions/upload-artifact@v3
      with:
        name: safety-results
        path: safety-results*.json