# AutoMatrix AI Hub - Alertmanager Configuration
# Generated: 2025-01-31

global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@autmatrix.com'
  smtp_auth_username: 'alerts@autmatrix.com'
  smtp_auth_password: 'your-email-password'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default-receiver'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
  - match:
      severity: warning
    receiver: 'warning-alerts'

receivers:
- name: 'default-receiver'
  email_configs:
  - to: 'ops@autmatrix.com'
    subject: 'AutoMatrix Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Labels: {{ range .Labels.SortedPairs }}{{ .Name }}={{ .Value }} {{ end }}
      {{ end }}

- name: 'critical-alerts'
  email_configs:
  - to: 'ops@autmatrix.com,admin@autmatrix.com'
    subject: '🚨 CRITICAL: AutoMatrix Alert - {{ .GroupLabels.alertname }}'
    body: |
      CRITICAL ALERT TRIGGERED
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.job }}
      Time: {{ .StartsAt }}
      {{ end }}
      
      Please investigate immediately.

- name: 'warning-alerts'
  email_configs:
  - to: 'ops@autmatrix.com'
    subject: '⚠️ WARNING: AutoMatrix Alert - {{ .GroupLabels.alertname }}'
    body: |
      WARNING ALERT TRIGGERED
      
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Severity: {{ .Labels.severity }}
      Service: {{ .Labels.job }}
      Time: {{ .StartsAt }}
      {{ end }}

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']