metadata:
  name: "service_advisor"
  description: "Template for service department and maintenance advising"
  category: "automotive"
  version: "1.0.0"
  author: "TuneDev"
  created_date: "2025-08-02"
  updated_date: "2025-08-02"
  tags:
    - "automotive"
    - "service"
    - "maintenance"
    - "advisor"
    - "technical"

template:
  task: "vertical-tune"
  vertical: "automotive"
  specialization: "service_advisor"
  model: "${model}"
  method: "${method}"
  dataset: "${dataset}"
  parameters:
    epochs: "${epochs}"
    learning_rate: "${learning_rate}"
    batch_size: "${batch_size}"
    lora_r: "${lora_r}"
    lora_alpha: "${lora_alpha}"
    lora_dropout: "${lora_dropout}"
    warmup_steps: "${warmup_steps}"
    weight_decay: "${weight_decay}"
    gradient_accumulation_steps: "${gradient_accumulation_steps}"
    max_grad_norm: "${max_grad_norm}"
  evaluation:
    metrics: "${metrics}"
    test_split: "${test_split}"
    validation_split: "${validation_split}"
    eval_steps: "${eval_steps}"
    eval_strategy: "${eval_strategy}"
  output:
    dir: "${output_dir}"
    format: "${output_format}"
    save_steps: "${save_steps}"
    save_strategy: "${save_strategy}"
  deployment:
    endpoint_type: "${endpoint_type}"
    quantization: "${quantization}"
    instance_type: "${instance_type}"
    instance_count: "${instance_count}"
    scaling_policy: "${scaling_policy}"
    min_instances: "${min_instances}"
    max_instances: "${max_instances}"
    auto_scaling_metrics: "${auto_scaling_metrics}"
    inference_timeout: "${inference_timeout}"

example:
  task: "vertical-tune"
  vertical: "automotive"
  specialization: "service_advisor"
  model: "mistral-7b"
  method: "QLoRA"
  dataset: "./datasets/maintenance_procedures.jsonl"
  parameters:
    epochs: 3
    learning_rate: 2e-4
    batch_size: 8
    lora_r: 16
    lora_alpha: 32
    lora_dropout: 0.05
    warmup_steps: 100
    weight_decay: 0.01
    gradient_accumulation_steps: 4
    max_grad_norm: 1.0
  evaluation:
    metrics: ["accuracy", "f1", "precision", "recall"]
    test_split: 0.1
    validation_split: 0.1
    eval_steps: 200
    eval_strategy: "steps"
  output:
    dir: "./checkpoints/mistral-service-advisor"
    format: "safetensors"
    save_steps: 500
    save_strategy: "steps"
  deployment:
    endpoint_type: "vllm"
    quantization: "int8"
    instance_type: "g4dn.xlarge"
    instance_count: 1
    scaling_policy: "request-count-based"
    min_instances: 1
    max_instances: 5
    auto_scaling_metrics: ["RequestCount", "CPUUtilization"]
    inference_timeout: 30

variables:
  - name: "model"
    description: "Base model to fine-tune"
    type: "string"
    options: ["mistral-7b", "llama-7b", "llama-13b", "gpt-j-6b", "phi-2", "gemma-7b"]
    default: "mistral-7b"
    required: true
    
  - name: "method"
    description: "Fine-tuning method"
    type: "string"
    options: ["QLoRA", "LoRA", "Full-Finetune", "Adapter"]
    default: "QLoRA"
    required: true
    
  - name: "dataset"
    description: "Path to dataset"
    type: "string"
    default: "./datasets/maintenance_procedures.jsonl"
    required: true
    
  - name: "epochs"
    description: "Number of training epochs"
    type: "integer"
    default: 3
    min: 1
    max: 10
    required: true
    
  - name: "learning_rate"
    description: "Learning rate"
    type: "number"
    default: 2e-4
    min: 1e-6
    max: 1e-2
    required: true
    
  - name: "batch_size"
    description: "Batch size"
    type: "integer"
    default: 8
    options: [1, 2, 4, 8, 16, 32]
    required: true
    
  - name: "lora_r"
    description: "LoRA r parameter (rank)"
    type: "integer"
    default: 16
    options: [4, 8, 16, 32, 64]
    required: true
    
  - name: "lora_alpha"
    description: "LoRA alpha parameter (scaling)"
    type: "integer"
    default: 32
    options: [8, 16, 32, 64, 128]
    required: true
    
  - name: "lora_dropout"
    description: "LoRA dropout"
    type: "number"
    default: 0.05
    min: 0
    max: 0.5
    required: true
    
  - name: "warmup_steps"
    description: "Number of warmup steps"
    type: "integer"
    default: 100
    min: 0
    max: 1000
    required: false
    
  - name: "weight_decay"
    description: "Weight decay for AdamW optimizer"
    type: "number"
    default: 0.01
    min: 0
    max: 0.1
    required: false
    
  - name: "gradient_accumulation_steps"
    description: "Number of gradient accumulation steps"
    type: "integer"
    default: 4
    min: 1
    max: 32
    required: false
    
  - name: "max_grad_norm"
    description: "Maximum gradient norm for gradient clipping"
    type: "number"
    default: 1.0
    min: 0.1
    max: 10.0
    required: false
    
  - name: "metrics"
    description: "Evaluation metrics"
    type: "array"
    items:
      type: "string"
      options: ["accuracy", "f1", "precision", "recall", "rouge", "bleu"]
    default: ["accuracy", "f1", "precision", "recall"]
    required: true
    
  - name: "test_split"
    description: "Test split ratio"
    type: "number"
    default: 0.1
    min: 0.05
    max: 0.3
    required: true
    
  - name: "validation_split"
    description: "Validation split ratio"
    type: "number"
    default: 0.1
    min: 0.05
    max: 0.3
    required: false
    
  - name: "eval_steps"
    description: "Evaluation steps"
    type: "integer"
    default: 200
    min: 50
    max: 1000
    required: false
    
  - name: "eval_strategy"
    description: "Evaluation strategy"
    type: "string"
    options: ["steps", "epoch", "no"]
    default: "steps"
    required: false
    
  - name: "output_dir"
    description: "Output directory for checkpoints"
    type: "string"
    default: "./checkpoints/mistral-service-advisor"
    required: true
    
  - name: "output_format"
    description: "Output format"
    type: "string"
    options: ["safetensors", "pytorch", "onnx"]
    default: "safetensors"
    required: true
    
  - name: "save_steps"
    description: "Save checkpoint steps"
    type: "integer"
    default: 500
    min: 100
    max: 5000
    required: false
    
  - name: "save_strategy"
    description: "Save checkpoint strategy"
    type: "string"
    options: ["steps", "epoch", "no"]
    default: "steps"
    required: false
    
  - name: "endpoint_type"
    description: "Inference endpoint type"
    type: "string"
    options: ["vllm", "triton", "tensorrt", "onnx", "tgi"]
    default: "vllm"
    required: true
    
  - name: "quantization"
    description: "Quantization method"
    type: "string"
    options: ["none", "int8", "int4", "gptq", "awq"]
    default: "int8"
    required: true
    
  - name: "instance_type"
    description: "Instance type for deployment"
    type: "string"
    options: ["g4dn.xlarge", "g5.xlarge", "c5.2xlarge", "p3.2xlarge", "p4d.24xlarge"]
    default: "g4dn.xlarge"
    required: true
    
  - name: "instance_count"
    description: "Number of instances"
    type: "integer"
    default: 1
    min: 1
    max: 10
    required: true
    
  - name: "scaling_policy"
    description: "Auto-scaling policy"
    type: "string"
    options: ["request-count-based", "latency-based", "cpu-based", "none"]
    default: "request-count-based"
    required: false
    
  - name: "min_instances"
    description: "Minimum number of instances for auto-scaling"
    type: "integer"
    default: 1
    min: 1
    max: 5
    required: false
    
  - name: "max_instances"
    description: "Maximum number of instances for auto-scaling"
    type: "integer"
    default: 5
    min: 1
    max: 20
    required: false
    
  - name: "auto_scaling_metrics"
    description: "Metrics for auto-scaling"
    type: "array"
    items:
      type: "string"
      options: ["RequestCount", "CPUUtilization", "GPUUtilization", "MemoryUtilization", "Latency"]
    default: ["RequestCount", "CPUUtilization"]
    required: false
    
  - name: "inference_timeout"
    description: "Inference timeout in seconds"
    type: "integer"
    default: 30
    min: 5
    max: 300
    required: false

use_cases:
  - name: "Maintenance Procedure Assistance"
    description: "Guide technicians through complex maintenance procedures with step-by-step instructions"
    dataset_requirements: "Maintenance manuals, repair procedures, technical bulletins, common issues and solutions"
    recommended_parameters:
      model: "mistral-7b"
      method: "QLoRA"
      batch_size: 8
      lora_r: 16
      
  - name: "Service Recommendation"
    description: "Provide service recommendations based on vehicle history, mileage, and known issues"
    dataset_requirements: "Service histories, maintenance schedules, common issues by make/model, technical service bulletins"
    recommended_parameters:
      model: "llama-7b"
      method: "QLoRA"
      batch_size: 4
      lora_r: 32
      
  - name: "Diagnostic Assistance"
    description: "Help technicians diagnose vehicle issues based on symptoms and diagnostic codes"
    dataset_requirements: "Diagnostic trouble codes, symptom descriptions, diagnostic procedures, repair histories"
    recommended_parameters:
      model: "llama-13b"
      method: "QLoRA"
      batch_size: 4
      lora_r: 32
      
  - name: "Customer Communication"
    description: "Generate clear explanations of technical issues and repairs for customer communication"
    dataset_requirements: "Technical-to-layman explanations, service advisor communications, customer interactions"
    recommended_parameters:
      model: "mistral-7b"
      method: "QLoRA"
      batch_size: 8
      lora_r: 16
      
  - name: "Parts Identification"
    description: "Identify correct parts needed for specific repairs and maintenance procedures"
    dataset_requirements: "Parts catalogs, vehicle specifications, repair procedures with parts lists"
    recommended_parameters:
      model: "mistral-7b"
      method: "QLoRA"
      batch_size: 8
      lora_r: 16

integration_points:
  - system: "Service Management System"
    description: "Integration with service department management systems"
    requirements: "API access, service history data, appointment scheduling, repair order management"
    
  - system: "Technical Information Systems"
    description: "Integration with OEM technical information systems and repair databases"
    requirements: "API access, authentication credentials, document retrieval capabilities"
    
  - system: "Parts Inventory System"
    description: "Integration with parts inventory and ordering systems"
    requirements: "API access, inventory queries, parts compatibility data, ordering capabilities"
    
  - system: "Diagnostic Equipment"
    description: "Integration with vehicle diagnostic systems and scan tools"
    requirements: "Data format specifications, diagnostic code libraries, real-time data access"
    
  - system: "RelayCore"
    description: "Integration with RelayCore platform for service data exchange"
    requirements: "RelayCore API credentials, connector configuration, data synchronization setup"

deployment_recommendations:
  development:
    instance_type: "g4dn.xlarge"
    quantization: "int8"
    scaling_policy: "none"
    
  testing:
    instance_type: "g4dn.xlarge"
    quantization: "int8"
    scaling_policy: "none"
    
  production:
    instance_type: "g5.xlarge"
    quantization: "int8"
    scaling_policy: "request-count-based"
    min_instances: 2
    max_instances: 10
    auto_scaling_metrics: ["RequestCount", "CPUUtilization", "Latency"]

technical_requirements:
  - "Access to OEM repair procedures and technical service bulletins"
  - "Integration with diagnostic trouble code databases"
  - "Access to vehicle-specific maintenance schedules"
  - "Parts catalog and compatibility data"
  - "Service history database access"
  - "Real-time integration with service management system"

domain_knowledge:
  - category: "Vehicle Systems"
    topics:
      - "Engine management systems"
      - "Transmission and drivetrain"
      - "Braking systems"
      - "Electrical systems"
      - "HVAC systems"
      - "Suspension and steering"
      - "Safety systems"
      
  - category: "Maintenance Procedures"
    topics:
      - "Routine maintenance schedules"
      - "Fluid replacement procedures"
      - "Component replacement guidelines"
      - "Calibration and adjustment procedures"
      - "Diagnostic workflows"
      
  - category: "Technical Standards"
    topics:
      - "OEM service standards"
      - "Safety protocols"
      - "Warranty requirements"
      - "Quality control procedures"
      - "Environmental compliance"