global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Auterity Frontend
  - job_name: 'auterity-frontend'
    static_configs:
      - targets: ['frontend:80']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'frontend'

  # Auterity Backend API
  - job_name: 'auterity-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 15s
    scrape_timeout: 10s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend'

  # PostgreSQL Database
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'postgres'

  # Redis Cache
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'redis'

  # Node.js Applications (Backend)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['backend:8000']
    scrape_interval: 30s
    metrics_path: '/metrics/node'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'backend-node'

  # Nginx Web Server
  - job_name: 'nginx'
    static_configs:
      - targets: ['frontend:80']
    scrape_interval: 30s
    metrics_path: '/metrics/nginx'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'nginx'

  # Docker Containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker:9323']
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'docker'

  # System Metrics
  - job_name: 'node'
    static_configs:
      - targets:
          - 'frontend:9100'
          - 'backend:9100'
          - 'postgres:9100'
          - 'redis:9100'
    scrape_interval: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '${1}'

  # Traefik Reverse Proxy
  - job_name: 'traefik'
    static_configs:
      - targets: ['traefik:8080']
    scrape_interval: 30s
    metrics_path: '/metrics'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'traefik'

  # Custom Business Metrics
  - job_name: 'auterity-business'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics/business'
    scrape_interval: 60s
    scrape_timeout: 30s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'business-metrics'
