# AutoMatrix AI Hub - Prometheus Configuration
# Generated: 2025-01-31

global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # AutoMatrix Backend
  - job_name: 'autmatrix-backend'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # RelayCore Service
  - job_name: 'relaycore'
    static_configs:
      - targets: ['relaycore:3001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # NeuroWeaver Backend
  - job_name: 'neuroweaver-backend'
    static_configs:
      - targets: ['neuroweaver-backend:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']