version: '3.8'

services:
  cost-aware-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: cost-aware-model-switching:production
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cost_aware_db
      - RELAYCORE_API_URL=${RELAYCORE_API_URL:-http://relaycore:3000}
      - AUTERITY_API_URL=${AUTERITY_API_URL:-http://auterity:3001}
      - ENABLE_INTEGRATIONS=${ENABLE_INTEGRATIONS:-false}
    depends_on:
      - redis
      - postgres
    restart: unless-stopped
    networks:
      - cost-aware-network
      - relaycore-network

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - cost-aware-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cost_aware_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
    networks:
      - cost-aware-network

networks:
  cost-aware-network:
    driver: bridge
  relaycore-network:
    external: true

volumes:
  redis-data:
  postgres-data: