# AutoMatrix AI Hub - Grafana Datasource Configuration
# Generated: 2025-01-31

apiVersion: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  url: http://prometheus:9090
  isDefault: true
  editable: true
