version: '3.8'

services:
  clickhouse:
    image: yandex/clickhouse-server:latest
    container_name: clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_MAX_MEMORY_USAGE=8GB  # Limit memory usage
    deploy:
      resources:
        limits:
          memory: 8GB
          cpus: '2.0'
    restart: always

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka-server
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-server:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_HEAP_OPTS: "-Xmx1g -Xms1g"  # Limit heap size
    depends_on:
      - zookeeper
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: '1.0'
    restart: always

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-server
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      JVMFLAGS: "-Xmx512m -Xms512m"  # Limit JVM memory
    deploy:
      resources:
        limits:
          memory: 512MB
          cpus: '0.5'
    restart: always

  superset:
    image: apache/superset:latest
    container_name: superset-server
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: 'your-secret-key'
      SUPERSET_LOAD_EXAMPLES: 'no'  # Disable examples for performance
    depends_on:
      - clickhouse
    deploy:
      resources:
        limits:
          memory: 2GB
          cpus: '1.0'
    restart: always

volumes:
  clickhouse_data:
  clickhouse_config:
