environment: development

# Deployment configuration
replicaCount:
  api: 1
  frontend: 1
  templateSystem: 1
  autoSpecializer: 1
  inferenceWeaver: 1
  datasetRefinement: 1
  costguardDashboard: 1
  workflowUi: 1

# Resource configuration - reduced for development
resources:
  api:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  frontend:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  templateSystem:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  autoSpecializer:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  inferenceWeaver:
    limits:
      cpu: 1000m
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi
  datasetRefinement:
    limits:
      cpu: 500m
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi
  costguardDashboard:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  workflowUi:
    limits:
      cpu: 250m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

# Ingress configuration
ingress:
  enabled: true
  hosts:
    - host: api.dev.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: api
    - host: app.dev.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: dashboard.dev.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: costguardDashboard
    - host: workflow.dev.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: workflowUi
  tls:
    - secretName: neuroweaver-dev-tls
      hosts:
        - api.dev.neuroweaver.io
        - app.dev.neuroweaver.io
        - dashboard.dev.neuroweaver.io
        - workflow.dev.neuroweaver.io

# Storage configuration
persistence:
  enabled: true
  storageClass: "gp2"
  size: 50Gi

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true

# Autoscaling configuration
autoscaling:
  enabled: false