environment: production

# Deployment configuration
replicaCount:
  api: 3
  frontend: 3
  templateSystem: 2
  autoSpecializer: 2
  inferenceWeaver: 3
  datasetRefinement: 2
  costguardDashboard: 2
  workflowUi: 2

# Resource configuration - increased for production
resources:
  api:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  frontend:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  templateSystem:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  autoSpecializer:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi
  inferenceWeaver:
    limits:
      cpu: 4000m
      memory: 16Gi
    requests:
      cpu: 2000m
      memory: 8Gi
  datasetRefinement:
    limits:
      cpu: 2000m
      memory: 4Gi
    requests:
      cpu: 1000m
      memory: 2Gi
  costguardDashboard:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  workflowUi:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi

# Ingress configuration
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: api.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: api
    - host: app.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: dashboard.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: costguardDashboard
    - host: workflow.neuroweaver.io
      paths:
        - path: /
          pathType: Prefix
          service: workflowUi
  tls:
    - secretName: neuroweaver-prod-tls
      hosts:
        - api.neuroweaver.io
        - app.neuroweaver.io
        - dashboard.neuroweaver.io
        - workflow.neuroweaver.io

# Storage configuration
persistence:
  enabled: true
  storageClass: "gp2"
  size: 500Gi

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
    retention: 30d
    resources:
      limits:
        cpu: 1000m
        memory: 2Gi
      requests:
        cpu: 500m
        memory: 1Gi
  grafana:
    enabled: true
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

# Autoscaling configuration
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70