# Default values for neuroweaver.
# This is a YAML-formatted file.

environment: development

# Image configuration
imageRegistry: ${AWS_ECR_REGISTRY}
imageTag: latest
imagePullPolicy: Always

# Deployment configuration
replicaCount:
  api: 1
  frontend: 1
  templateSystem: 1
  autoSpecializer: 1
  inferenceWeaver: 1
  datasetRefinement: 1
  costguardDashboard: 1
  workflowUi: 1

# Resource configuration
resources:
  api:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  frontend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  templateSystem:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  autoSpecializer:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 4Gi
  inferenceWeaver:
    limits:
      cpu: 2000m
      memory: 8Gi
    requests:
      cpu: 1000m
      memory: 4Gi
  datasetRefinement:
    limits:
      cpu: 1000m
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  costguardDashboard:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  workflowUi:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

# Service configuration
service:
  api:
    type: ClusterIP
    port: 8000
  frontend:
    type: ClusterIP
    port: 80
  templateSystem:
    type: ClusterIP
    port: 8001
  autoSpecializer:
    type: ClusterIP
    port: 8002
  inferenceWeaver:
    type: ClusterIP
    port: 8003
  datasetRefinement:
    type: ClusterIP
    port: 8004
  costguardDashboard:
    type: ClusterIP
    port: 8050
  workflowUi:
    type: ClusterIP
    port: 8080

# Ingress configuration
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: api.${DOMAIN}
      paths:
        - path: /
          pathType: Prefix
          service: api
    - host: app.${DOMAIN}
      paths:
        - path: /
          pathType: Prefix
          service: frontend
    - host: dashboard.${DOMAIN}
      paths:
        - path: /
          pathType: Prefix
          service: costguardDashboard
    - host: workflow.${DOMAIN}
      paths:
        - path: /
          pathType: Prefix
          service: workflowUi
  tls:
    - secretName: neuroweaver-tls
      hosts:
        - api.${DOMAIN}
        - app.${DOMAIN}
        - dashboard.${DOMAIN}
        - workflow.${DOMAIN}

# Storage configuration
persistence:
  enabled: true
  storageClass: "gp2"
  size: 100Gi

# Database configuration
database:
  host: ${DB_HOST}
  port: ${DB_PORT}
  name: ${DB_NAME}
  user: ${DB_USER}
  password: ${DB_PASSWORD}

# Redis configuration
redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}

# S3 configuration
s3:
  bucket: ${S3_BUCKET}
  region: ${AWS_REGION}

# Monitoring configuration
monitoring:
  enabled: true
  prometheus:
    enabled: true
  grafana:
    enabled: true
    adminPassword: ${GRAFANA_PASSWORD}

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80