version: '3.8'

services:
  template-system:
    build:
      context: .
      dockerfile: docker/template-system/Dockerfile
    volumes:
      - ./src/template-system:/app/src/template-system
      - ./vertical_kits:/app/vertical_kits
    command: python -m src.template-system.tools.validate_templates --directory vertical_kits/automotive/templates

  auto-specializer:
    build:
      context: .
      dockerfile: docker/auto-specializer/Dockerfile
    volumes:
      - ./src/models/specializer:/app/src/models/specializer
      - ./vertical_kits:/app/vertical_kits
      - ./datasets:/app/datasets
      - ./checkpoints:/app/checkpoints
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  inference-weaver:
    build:
      context: .
      dockerfile: docker/inference-weaver/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./src/models/inference:/app/src/models/inference
      - ./checkpoints:/app/checkpoints
    environment:
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  costguard-dashboard:
    build:
      context: .
      dockerfile: docker/costguard-dashboard/Dockerfile
    ports:
      - "8050:8050"
    volumes:
      - ./src/frontend/components:/app/src/frontend/components
    depends_on:
      - inference-weaver

  workflow-ui:
    build:
      context: .
      dockerfile: docker/workflow-ui/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./src/frontend/components:/app/src/frontend/components
    depends_on:
      - template-system
      - auto-specializer