
# amazon-q-sso-config.yaml

authentication:
  method: "SAML2.0 or OIDC"
  fallback: false
  mfa:
    enforced: true
    delegated_to_idp: true

idp:
  name: "Enterprise Identity Provider"
  entity_id: "https://your-idp.com"
  sso_url: "https://your-idp.com/sso/login"
  certificate: "MIID...<Base64 encoded X.509 cert>"
  metadata_url: "https://your-idp.com/metadata.xml"
  attributes:
    - email
    - name
    - groups
    - roles

iam_identity_center:
  enabled: true
  session_duration_hours: 8
  attribute_mapping:
    email: "user.email"
    groups: "user.groups"
    roles: "user.roles"

roles:
  - name: "Admin"
    permissions: ["full_access"]
  - name: "Developer"
    permissions: ["q_developer_access"]
  - name: "Data Analyst"
    permissions: ["q_business_read"]
  - name: "Compliance Officer"
    permissions: ["view_audit_logs"]
  - name: "CustomRole"
    permissions: ["custom_defined_permissions"]

logging:
  enabled: true
  services:
    - "CloudTrail"
    - "Amazon Q Admin Logs"
  retention_days: 90

testing:
  scenarios:
    - "login_success"
    - "role_mapping"
    - "mfa_challenge"
    - "expired_session"
    - "logging_validation"

deployment:
  phases:
    - name: "Phase 1"
      task: "Configure SSO in Amazon Q or IAM Identity Center"
    - name: "Phase 2"
      task: "Sync roles and attributes with IdP"
    - name: "Phase 3"
      task: "Pilot testing"
    - name: "Phase 4"
      task: "Enterprise rollout"
    - name: "Phase 5"
      task: "Monitoring and iteration"
